### ISSUE TITLE
Geyser education command does not work

### ISSUE THREAD

**Issue by dannytech** [bundabrg/GeyserReversion#8]
Sorry for the issue spam, I've been facing surprisingly few issues getting this set up besides this and the other issue.

Running v1.16-31b of your Geyser build and v1.0.11 of GeyserReversion, I'm unable to use the `/geyser education` command. On the Waterfall console, `/geyser education new` has the same explanatory output as `/geyser education`. From the [source](https://github.com/bundabrg/GeyserReversion/blob/d8f75538c235a16ddc66180887e30fe99fa73b16/geyser-reversion/src/main/java/au/com/grieve/geyser/reversion/editions/education/commands/EducationCommand.java#L48-L50), it looks like it's not supposed to work from ingame, but with the console not working and ingame not being a possibility I'm not sure what I can do. I suspect the error is due to an incorrect index in the arguments [here](https://github.com/bundabrg/GeyserReversion/blob/d8f75538c235a16ddc66180887e30fe99fa73b16/geyser-reversion/src/main/java/au/com/grieve/geyser/reversion/editions/education/commands/EducationCommand.java#L57) but could be wrong about that.

If I face any further issues I'll try to get a development environment set up and fix them myself so my contributions aren't just GitHub issues.

**Comment by bundabrg** [comment]
I think it may be a bug in how Geyser handles commands. It looks like it may be passing the parameters different for the different platforms. I've test with standalone so it'll need some testing to see how it differs. I suspect standalone strips off the command from the front whereas it looks like BungeeCord for example keeps it on which would explain your symptoms. I'll raise an issue there and have a look when I get a chance.

Definitely fire up a dev environment if you have time. It would be nice to have another person for testing etc since this is presently a solo job.

**Comment by dannytech** [comment]
Went ahead and set up a dev environment (been a while since I've messed with Java to be honest), and looks like you're absolutely right. `args[0]` on Geyser under Waterfall is `education`, so looks like only `geyser` is stripped off. Could probably detect when it's `education` to handle this edge case, but I'm guessing there's some way to detect whether Geyser is standalone or running under something? I'm happy to act as a testbed for Bungee since I have an environment for that, but no clue how the behavior is under Spigot.

**Comment by dannytech** [comment]
Until this is fixed upstream, I've made a workaround [here](https://github.com/ChamplainMinecraft/GeyserReversion/commit/c4bf533d2e258943d295f1b8c81eb119f7223e9f).
